version: "2"
services:

  nginx:
    image: samanthajayasinghe/php-dev-env-nginx
    ports:
      - "80:80"
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
    networks:
       - php-dev

  php-5.6:
    image: samanthajayasinghe/php-dev-env-php56
    working_dir: ${REMOTE_SRC}
    environment:
      HIST_FILE: /root/.bash_history
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - $HOME/.bash_history:/root/.bash_history
    networks:
      - php-dev

volumes:
    pgsql-data:
    mssql-data:
    web-data:

networks:
  php-dev:
